//
// Created by Stif on 05.05.2023.
//

#ifndef LAB_2_INDEXOUTOFRANGEEXCEPTION_H
#define LAB_2_INDEXOUTOFRANGEEXCEPTION_H


class IndexOutOfRange{
public:
};

#endif //LAB2_INDEXOUTOFRANGEEXCEPTION_H
